- .gitignore
- .travis.yml
- schema_salad/jsonld_context.py
- schema_salad/makedoc.py
- schema_salad/ref_resolver.py
- schema_salad/schema.py
- tox.ini
The CI testing is probably un-controversial.
Python 2.6 is no longer supported by the Python project and dictionary comprehensions are cleaner in most cases then what I replaced them with - but these inconveniences are small compared to the fact that:
- RHEL 6 is still pervasive at academic institutions including HPC centers we would like to run CWL workflows.
- The Galaxy project still provides wide support for Python 2.6 including the core project and Planemo. I'd like unconditional support for cwl in both applications so I'd like cwltool to support Python 2.6 and hence this project.
Fixes https://github.com/common-workflow-language/galaxy/issues/19, xref https://github.com/galaxyproject/planemo/issues/411.
> Extended CI Testing and Python 2.6 Support

- README.rst
- requirements.txt
- schema_salad/jsonld_context.py
- schema_salad/main.py
- schema_salad/makedoc.py
- schema_salad/ref_resolver.py
- schema_salad/schema.py
- schema_salad/validate.py
- setup.py
- tests/test_examples.py
This is a fix for https://github.com/common-workflow-language/cwltool/issues/61
> switch to ruamel.yaml, use C loader if available, only load safely

- schema_salad/jsonld_context.py
- schema_salad/main.py
- schema_salad/metaschema/metaschema_base.yml
- schema_salad/ref_resolver.py
- schema_salad/schema.py
- setup.py
- tests/test_examples.py
Add test to support "unscoped" identifiers, these are object identifiers that follow the normal relative URI reference path join rules instead of schema salad's scoped document fragment identifiers.  This is used for the "location" field of File and Directory.
> Unscoped ids

- requirements.txt
- schema_salad/ref_resolver.py
- setup.py
Pathlib2 creates dependency issues that outweigh its benefit.
> Remove pathlib2 because it is only used for one thing 

- schema_salad/schema.py
Strips ruamel.yaml metadata, avoids unnecessary copies, and uses shallow copies.
> Fix performance regression in schema loading

- schema_salad/sourceline.py
- schema_salad/validate.py
These are debugging helpers for problematic CWL inputs, helping with
ongoing work debugging CWL Toil runs on AWS.
- Avoids failing on LineCol inputs that do not have file and
position references. Without this in place the missing `filename` and
None attributes for `line` and `col` obscure the real error message.
Fixes common-workflow-language/cwltool#264
- Prints out value of a CWL data item that is not an expected list.
> Improve debugging: missing filename and bad lists

- schema_salad/main.py
- schema_salad/tests/test_cli_args.py
``--version`` does not need to go in a mutually exclusive group. added ``nargs`` to make positional arguments optional.
``` bash
(venv) manu@hp:~/github/schema_salad$ schema-salad-tool -h
usage: schema-salad-tool [-h] [--rdf-serializer RDF_SERIALIZER]
[--print-jsonld-context | --print-rdfs | --print-avro | --print-rdf | --print-pre | --print-index | --print-metadata]
[--strict | --non-strict]
[--verbose | --quiet | --debug] [--version]
[schema] [document]
positional arguments:
schema
document
optional arguments:
-h, --help            show this help message and exit
--rdf-serializer RDF_SERIALIZER
Output RDF serialization format used by --print-rdf
(one of turtle (default), n3, nt, xml)
--print-jsonld-context
Print JSON-LD context for schema
--print-rdfs          Print RDF schema …
```
> schema_salad/main.py: --version now correctly prints version

- MANIFEST.in
- schema_salad/ref_resolver.py
- schema_salad/validate.py
Import sets both "id" and "name" and then the id collision check causes it to collide with itself.  Oops.
> Fix for self-colliding ids on $import

- schema_salad/ref_resolver.py
Fixes common-workflow-language/cwltool#433
I would ideally also then want to remove "Did you include a $schemas section" from `validate.py` - but we don't know if the user want to do a strict vs non-strict.
> Optional skip_schemas

- schema_salad/makedoc.py
- schema_salad/ref_resolver.py
Leads to more consistant behaviour across py2 and py3
also, specify encoding in the open command rather than
reading raw bytes and manually decoding
> use io.open instead of builtin open

- schema_salad/__init__.py
- schema_salad/utils.py
Fixes https://github.com/common-workflow-language/cwltool/issues/499
Closes https://github.com/common-workflow-language/cwltool/pull/504
> [WIP] Fix windows installation error due to absence of \tmp folder

- schema_salad/ref_resolver.py
- schema_salad/tests/test_ref_resolver.py
..as the previous code had buggy handling of resolving "http" URIs from
a "file" (e.g. a $schemas)
Also added unit tests and more special cases for relative drive:/ path
handling. UNC paths not tested - I don't think those work well anyway..
This fixes #129 and (for both windows and unix) #130
> Refactor Windows relative path support

- schema_salad/main.py
This request adds `--print-oneline` option to print each error message in oneline.
It makes us easier to develop tools that integrate the validators and IDEs (or editors): for example, [on-the-fly syntax checker in Emacs](http://www.flycheck.org/) for Common Workflow Language.
I confirmed this request does not introduce new errors in `make mypy2` and `make mypy3`.
Currently `schema_salad_tool` prints good error messages with indents and newlines for user-readability.
For instance:
```console
$ schema_salad_tool /path/to/v1.0/CommonWorkflowLanguage.yml sample.cwl
While validating document `sample.cwl`:
sample.cwl:3:1: Object `sample.cwl` is not valid because
tried `CommandLineTool` but
sample.cwl:6:1:     the `inputs` field is not valid because
sample.cwl:7:3:       item is invalid because …
```
> Add --print-oneline option

- schema_salad/makedoc.py
- schema_salad/tests/test_examples.py
- schema_salad/utils.py
This request fixes the following errors by pylint.
```console
schema_salad/makedoc.py:329:21: E741 ambiguous variable name 'l'
schema_salad/utils.py:30:5: E741 ambiguous variable name 'l'
schema_salad/tests/test_examples.py:25:9: E741 ambiguous variable name 'l'
schema_salad/tests/test_examples.py:392:9: E722 do not use bare except'
schema_salad/tests/test_examples.py:400:9: E722 do not use bare except'
```
Here are more details:
> schema_salad/makedoc.py:329:21: E741 ambiguous variable name 'l'
- `l` -> `line`
- There is a variable named `lines` near this code. Other name may be better.
> schema_salad/utils.py:30:5: E741 ambiguous variable name 'l'
- `l` -> `lst`
> schema_salad/tests/test_examples.py:25:9: E741 ambiguous variable name 'l'
- `l` -> `loader`
> …
> Fix for pylint

- schema_salad/main.py
- schema_salad/tests/test_print_oneline.py
- schema_salad/tests/test_schema/test17.cwl
This request fix to show a better message for `--print-oneline` in which it handles itemize better.
Here is the example:
```yaml
class: CommandLineTool
cwlVersion: v1.0
baseCommand: cowsay
inputs:
- id: input
type: string?
inputBinding:
position: 0
outputs:
- id: output
type: string?
outputBinding: {}
- aa: moa
```
Without `--print-oneline`, we see the following messages:
```console
While validating document `echo.cwl`:
echo.cwl:1:1: Object `echo.cwl` is not valid because
tried `CommandLineTool` but
echo.cwl:9:1:     the `outputs` field is not valid because
echo.cwl:13:5:       item is invalid because
* missing required field `id`
* invalid field `aa`, expected one of: 'label', 'secondaryFiles',
'streamable', 'doc', 'id', 'outputBinding', 'format', 'type'
```
We expect for …
> Better itemize handling for `--print-oneline`

- schema_salad/main.py
- schema_salad/tests/test_print_oneline.py
- schema_salad/tests/test_schema/test18.cwl
`salad-schema-tool` with `--print-oneline` prints unintended oneline output with the following CWL file.
```yaml
class: CommandLineTool
cwlVersion: v1.0
baseCommand: echo
inputs:
- id: input
type: string?
inputBinding: {}
outputs:
- id: output
type: string?
outputBinding: {}
- id: output1
type: Filea
```
Without `--print-oneline` (actual output):
```console
test18.cwl:8:1: checking field `outputs`
test18.cwl:12:5:   checking object `test18.cwl#output1`
test18.cwl:13:5:     Field `type` references unknown identifier `Filea`, tried
file:///Users/tom-tan/repos/schema_salad/schema_salad/tests/test_schema/test18.cwl#Filea
```
Expected with `--print-oneline`:
```console
test18.cwl:13:5: Field `type` references unknown identifier `Filea`, tried …
```
> Fix error message for resolve_ref with --print-oneline

- schema_salad/main.py
- schema_salad/tests/test_print_oneline.py
As I described in #141, the output with `--print-oneline` for `test18.cwl` needs a space between the place where the error happens and the error message.
This request fixes `main.py` and the test case for `--print-oneline`.
Before:
```console
test18.cwl:13:5:Field `type` references unknown identifier `Filea`, tried file:///Users/tom-tan/repos/schema_salad/schema_salad/tests/test_schema/test18.cwl#Filea
```
After merging this request:
```console
test18.cwl:13:5: Field `type` references unknown identifier `Filea`, tried file:///Users/tom-tan/repos/schema_salad/schema_salad/tests/test_schema/test18.cwl#Filea
```
> Add space between filename and message for `--print-oneline`

- schema_salad/main.py
- schema_salad/tests/test_print_oneline.py
- schema_salad/tests/test_schema/test19.cwl
This request unifies the format for error message due to invalid YAMLs.
Currently `schema-salad-tool` uses the following format for error messages in most cases (e.g. `test15.cwl` in this repository):
```console
While validating document `test15.cwl`:
test15.cwl:3:1: Object `test15.cwl` is not valid because
tried `CommandLineTool` but
test15.cwl:6:1:     the `inputs` field is not valid because
test15.cwl:7:3:       item is invalid because
test15.cwl:9:5:         the `inputBinding` field is not valid because
tried CommandLineBinding but
test15.cwl:11:7:             * invalid field `invalid_field`, expected one of:
'loadContents', 'position', 'prefix', 'separate', 'itemSeparator',
'valueFrom', 'shellQuote'
test15.cwl:12:7:             * invalid field `another_invalid_field`, expected one …
```
> Unify the error message format for invalid YAML

- schema_salad/main.py
Fixes formatting of RDF output on Python 3.
> main: print string instead of bytes

- schema_salad/ref_resolver.py
This else case was missing a wrapping `os.path.join()`
Fixes #158
> Corrects initializer to FileCache when no TMP or HOME

- schema_salad/sourceline.py
When different lines as part of the same message reference have
different line numbers or files (such as messages from a static
checker referencing different parts of a document), normalize to the
maximum leading length to preserve relative indentation among lines.
> Preserve relative indentation between lines

- .gitignore
- schema_salad/ref_resolver.py
- schema_salad/tests/test_errors.py
Related common-workflow-language/common-workflow-language#734
After merged, common-workflow-language/common-workflow-language should
```
git submodule update --remote
```
> Fix inconsistent definition with cwl files in CWL

- schema_salad/makedoc.py
- schema_salad/metaschema.py
- schema_salad/python_codegen_support.py
- schema_salad/ref_resolver.py
- schema_salad/validate.py
Fixes
```
schema_salad/metaschema.py:463:16: W605 invalid escape sequence '\['
schema_salad/metaschema.py:463:18: W605 invalid escape sequence '\]'
schema_salad/metaschema.py:463:23: W605 invalid escape sequence '\?'
schema_salad/python_codegen_support.py:266:16: W605 invalid escape sequence '\['
schema_salad/python_codegen_support.py:266:18: W605 invalid escape sequence '\]'
schema_salad/python_codegen_support.py:266:23: W605 invalid escape sequence '\?'
schema_salad/validate.py:223:19: W504 line break after binary operator
schema_salad/ref_resolver.py:216:25: W504 line break after binary operator
schema_salad/ref_resolver.py:368:17: W504 line break after binary operator
schema_salad/ref_resolver.py:370:17: W504 line break after binary operator
schema_salad/ref_resolver.py:656:16: W605 …
```
> flake8 got more strict

- schema_salad/metaschema/metaschema.yml
- schema_salad/ref_resolver.py
- schema_salad/tests/metaschema-pre.yml
- schema_salad/tests/test_examples.py
Add `secondaryFilesDSL` which behaves similarly to `typeDSL` in expanding a compact string into an object.
> Mini-DSL for optional secondary files.

- schema_salad/ref_resolver.py
Because CommentedMap.copy() returns a dict!  Argh!
> Use copy.copy(CommentedMap) instead of CommentedMap.copy()

- Makefile
- schema_salad/ref_resolver.py
- setup.py
Turns out copy.copy() on a CommentedMap doesn't do the same thing across 2.7 and 3+
Also I realized because resolve_all()/resolve_ref() are called recursively it would tend to inefficiently make a lot of unnecessary copies.
> Copying metadata to be backwards compatible was a mistake.

- schema_salad/main.py
- schema_salad/sourceline.py
This request moves `to_one_line_messages` and related functions from `main.py` to `sourceline.py`.
These functions are also useful in code-generated script.
This change does not break any user scripts that use `schema-salad-tool` and does not break any existing codes that use code-generated scripts without modifications.
> Move `main.to_one_line_messages` and related functions to `sourceline.py`

- schema_salad/tests/test_errors.py
This request is to add tests for `ValidationException` for `test2.cwl` to `test15.cwl` (a test for `test1.cwl` was done by #232).
This request is currently work in progress and not to merge.
The reason why I sent this unfinished pull request is to know the exact error messages for each CI testers.
As mentioned in the [comment in #232](https://github.com/common-workflow-language/schema_salad/pull/232#issuecomment-460544860), we have to execute the test for all CI testers to make a test for current `ValidationException`.
Here is a list of tests to be done by this request. Once all the tests are written and passed by all the CI testers, I remove the [WIP] tag and will be ready to merge.
I will add a test for each CWL file to mach the generated error message and a simple regular expression …
> Add tests for ValidationException

- schema_salad/python_codegen.py
This request adds `load_document_by_string` that takes a content of a CWL document rather than URI or relative path of the document to be loaded.
We are working on a [cwl-language-server](https://github.com/common-workflow-language/cwl-language-server) and currently we are start adding `publishDiagnostics` (It is to add syntax checking feature) by using a python module that is generated by `schema-salad-tool --codegen python`.
According to the [spec of language server protocol](https://microsoft.github.io/language-server-protocol/specification#textDocument_didOpen), language servers have to manage the content of the document by using notifications from a client (i.e., editors and IDEs etc) and they should not read the document directly.
However, the code-generated module does not provide …
> Add `load_document_by_string` for codegen

- Makefile
- schema_salad/validate.py
- setup.py
Eliminate workaround of requiring both "string" and "Expression" even
when a string value wasn't meaningful.
refs #39
> Special case validation for 'Expression'

- schema_salad/python_codegen_support.py
This request partially solves the error message from the code generated parser.
```console
$ schema-salad-tool --codegen python /path/to/common-workflow-language/v1.0/CommonWorkflowLanguage.yml > v1_0.py
$ cat <<EOS > validate.py
from v1_0 import load_document
import sys
if __name__ == '__main__':
try:
load_document(sys.argv[1])
except Exception as e:
print(e)
EOS
$ sed 's/cwlVersion: v1.0/cwlVersion: v1.0a/' /path/to/common-workflow-language/v1.0/v1.0/bwa-mem-tool.cwl > error.cwl
$ python validate.py error.cwl
```
```console
- tried <class 'v1_0.CommandLineTool'> but
Trying 'CommandLineTool'
error.cwl:3:1:     the `cwlVersion` field is not valid because:
error.cwl:3:1:     - tried <class 'NoneType'> but
error.cwl:3:1:         Expected a <class 'NoneType'> but got <class 'str'> …
```
> Use `T` rather than `<class 'T'> ` in errors from codegen-ed parser

- schema_salad/ref_resolver.py
- schema_salad/tests/test_ref_resolver.py
Callback takes the first document in the stream, can use document
version or dev flags to decide if attachments should be allowed.
> Enable attachments optionally based on callback.

- .travis.yml
- Makefile
- schema_salad/avro/schema.py
- schema_salad/codegen.py
- schema_salad/exceptions.py
- schema_salad/jsonld_context.py
- schema_salad/main.py
- schema_salad/makedoc.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
- schema_salad/ref_resolver.py
- schema_salad/schema.py
- schema_salad/validate.py
> root the exception hierarchy in ValidationException

- schema_salad/sourceline.py
It is a preparation to solve #244.
It does not introduce any breaking changes.
It introduces `file`, `line` and `column` methods to `SourceLine` and refactors `SourceLine#makeLead` by using these methods.
By making `file`, `line` and `column` accessible to other classes, `ValidationException` will provide these information without parsing exception messages in further PRs.
> Refactor SourceLine#makeLead

- schema_salad/exceptions.py
- schema_salad/main.py
- schema_salad/metaschema.py
- schema_salad/python_codegen_support.py
- schema_salad/ref_resolver.py
- schema_salad/schema.py
- schema_salad/sourceline.py
- schema_salad/tests/test_errors.py
- schema_salad/validate.py
It is to solve #244 by introducing tree structured exception instead of manipulating strings.
I introduce the following API to `SchemaSaladException`:
```python
class SchemaSaladException(Exception):
self.file # type: Text: file name where an error occurs
self.start # type: Optional[Tuple[int, int]]: it consists of (line, column) where an error token starts
self.end # type: Optional[Tuple[int, int]]: where an error token ends (for future extensions)
self.children # type: Sequence[SchemaSaladException]
def str(self):
"""Returns a nice string as same as before. It internally uses `pretty_str()` method."""
pass
```
I also introduce two functions in `sourceline.py`: `reflow_all` and `strip_duplicated_lineno`.
`reflow_all` is to apply `reflow` for all lines. `strip_duplicated_lineno` is almost …
> Tree structured exception

- schema_salad/ref_resolver.py
- schema_salad/tests/test_ref_resolver.py
This request makes to use `ValidationException` for errors in schema-salad.
Using `ValidationException` (i.e. subclass of `SchemaSaladException`) rather than built-in exceptions provides users with a unified way to handle the exceptions from schema-salad.
> Use ValidationException rather than RuntimeError and ValueError

- schema_salad/exceptions.py
- schema_salad/sourceline.py
This request is for refactoring of `SourceLine`.
- Introduce `start` and `end` method instead of `line` and `column`
- `start` returns a tuple of `line` and `column` if `file` is present. Otherwise returns `None`
- `end` is for future extensions. Currently it always returns `None`
> Refactoring of accessors for SourceLine

- schema_salad/main.py
- schema_salad/makedoc.py
- schema_salad/ref_resolver.py
- schema_salad/schema.py
- schema_salad/tests/test_print_oneline.py
It continues #288.
By merging this request, all the exceptions thrown by schema salad (including exceptions from `ruamel.yaml` parser) can be caught as `SchemaSaladException`.
Here is a list of the next step:
- Make tests robust by using `SchemaSaladException#message` and `SchemaSaladException#start`
- Simplify `to_one_line_messages` using tree structured exception
- Cleanup code
- Now some functions can be safely removed (e.g. `reformat_yaml_exception_message` and `SourceLine#__enter__`)
> Use ValidationException instead of RuntimeError and ValueError

- schema_salad/exceptions.py
- schema_salad/main.py
- schema_salad/ref_resolver.py
- schema_salad/sourceline.py
- schema_salad/tests/test_print_oneline.py
This request simplifies `to_one_line_messages` by using tree structured exception instead of string manipulations.
Here is a list of main changes:
- Change the interface of `to_one_line_messages` from `(str) -> str` to `(SchemaSaladException) -> Text`
- Move the definition of `to_one_line_messages` from `sourceline.py` to `exceptions.py` to prevent a circular reference.
- *Change the intension of `SchemaSaladException#bullet`*
- Before: `bullet` is a bullet string to be added to `children`
- After: `bullet` is a bullet string to be added to `self`. It will be set by its parent
- Add `SchemaSaladException#summary` and `SchemaSaladException#leaves`
- `SchemaSaladException#summary(level: int, with_bullet: bool) -> Text` returns a one line summary of the exception using its `line`, `colum`, …
> Refactor SchemaSaladException and to_one_line_messages

- schema_salad/python_codegen_support.py
Three commits, three cleanups to bring inline with Java codegen I did:
- The schema parsing stuff looks to be wrong and isn't used anywhere as far as I can tell.
- Type annotation for resolving typedsl strings can be tightened up based on how the function is called and what it is assuming about its inputs otherwise.
- Eliminate a defensive code block in expand_url - the type annotation already says it is a string-ish type - don't need to re-check I assume.
> Clean up Python code generation.

- schema_salad/python_codegen.py
Tried adding the ``errors`` attribute from Galaxy workflow format to the schema and it crashed for obvious reasons. I do a similar thing in the Java codegen to prevent collisions.
> python codegen - allow a schema with errors attribute name

- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
Turns Galaxy workflows have a field name somewhere for each Python variable we're using during codegen.
A smarter approach might be like a local scope block - I was thinking abou that for Java. But it seems it isn't even a valid concept in Python (https://stackoverflow.com/questions/6167923/block-scope-in-python).
Similar approach used in https://github.com/common-workflow-language/schema_salad/pull/308.
> python codegen - allow fields named uuid.

- schema_salad/makedoc.py
This solves a problem with loading a external css file on:
https://www.commonwl.org/v1.1/
https://www.commonwl.org/v1.0/
> Correct attribute for "relation" on link elements

- schema_salad/codegen.py
- schema_salad/codegen_base.py
- schema_salad/java_codegen.py
- schema_salad/python_codegen.py
Hi @mr-c, @tetron, per the discussion in:
- Closes: https://github.com/common-workflow-language/schema_salad/issues/262
- https://github.com/common-workflow-language/python-cwlgen/issues/27
- Discussed in [2020-05-12 EMEA-Americas Common Workflow Language meeting notes](https://docs.google.com/document/d/1BsUKJzUiOJw8SjEF0fuiXxFgBY8gMBgRhZHF2x5b53M/edit)
This adds extra annotations to the schema salad python codegen to make parameters that are not required, optional within the class initialiser. 
Before: 
```python
class Workflow(Process):
def __init__(self, inputs, outputs , steps, id, label, doc, requirements, hints, cwlVersion, extension_fields, loadingOptions):
pass # init code here
```
After:
> Note, this isn't the actual generated code due to the codegen injecting type annotations …
> Make non-required parameters in Python codegen optional (=None)

- schema_salad/codegen.py
- schema_salad/codegen_base.py
- schema_salad/java_codegen.py
- schema_salad/python_codegen.py
Alas, we can try again once the parsing / order bug shown at https://github.com/common-workflow-language/cwl-utils/pull/14 is fixed
This reverts commit 5b494860842eac06a428bb891aef0bab3b0460a7.
> Revert "Make non-required parameters in Python codegen optional 

- schema_salad/codegen.py
- schema_salad/codegen_base.py
- schema_salad/java_codegen.py
- schema_salad/python_codegen.py
Reopens  #330
Thanks @mr-c for testing this in CWLUtils. Unfortunately the parameter reordering broke the parsing. I've added https://github.com/common-workflow-language/schema_salad/commit/b9a30fff334dc135845fcfb0b0e092d1a3acfa78 to address this problem by making `doc.load` to use kwargs (named arguments) instead of the original ordered arguments. 
I'll issue a CWL-utils PR with the updated generated code and hopefully travis will pass these to show this fix.
> Optional codegen args

- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
- schema_salad/tests/formattest2.cwl
- schema_salad/tests/test_examples.py
- schema_salad/tests/test_schemas_directive.py
This addresses https://github.com/common-workflow-language/schema_salad/issues/345
$schemas should be accepted and added to the loadingOptions
> Allow $schemas in codegen

- schema_salad/java/main_utils/EnumLoader.java
Doesn't process union types that include enums properly without this.
> javacodegen: Fix exception handling of enum loader.

- schema_salad/python_codegen_support.py
Fix URILoader when in a union type that includes arrays of objects.  refs #359
> Raise validation exception if element in list of URIs is not a string.

- schema_salad/makedoc.py
Fix:
```
schema-salad-doc --brandstyle '<link rel="stylesheet" href="https://jamestaylor.org/galaxy-bootstrap/galaxy_bootstrap.css">' --brandinverse --brand '<img src="icon.png" />' --only https://galaxyproject.org/gxformat2/v19_09#WorkflowDoc --only https://galaxyproject.org/gxformat2/v19_09#GalaxyWorkflow workflow.yml
Traceback (most recent call last):
File "/home/soranzon/software/nsoranzo_gxformat2/.venv/bin/schema-salad-doc", line 8, in <module>
sys.exit(main())
File "schema_salad/makedoc.py", line 695, in main
File "schema_salad/makedoc.py", line 730, in makedoc
TypeError: str object expected; got list
```
> Fix type annotation of renderlist

- .github/workflows/wheels.yml
- schema_salad/avro/schema.py
- schema_salad/schema.py
- schema_salad/utils.py
Fixes #385 
Due to recent binary wheel publishing using mypyc. Issue troubleshooting complicated due to lack of published Python 3.9 binary wheel for schema-salad; which this PR works around https://github.com/RalfG/python-wheels-manylinux-build/pull/33 not being released yet
Locally I tested this by using a Python 3.7 virtualenv; ensuring that one of the manylinux binary wheels was installed from https://pypi.org/project/schema-salad/7.1.20210316164414/#files and running 
`cwltool https://github.com/ncbi/pgap/raw/b56520bb683f8b795974f32d19bdcae09b84e590/task_types/tt_kmer_top_n_extract.cwl --gcextract2_sqlite README.rst --ref_assembly_id 0 --ref_assembly_taxid 0 --taxon_db README.rst --top_distances README.rst`
Without this fix I am able to reproduce the error in #385
Locally I did a …
> JSON float type

- requirements.txt
- setup.py
The original type annotation bug had been fixed in 0.16.6 (https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/CHANGES). 0.17 contains some breaking changes, hence the pin <0.17.
> Pin ruamel.yaml below 0.17, exclude 0.16.6

- schema_salad/metaschema.py
- schema_salad/python_codegen_support.py
Inspired by https://github.com/common-workflow-language/cwl-utils/issues/71
> pycodgen: fix loading of long form secondaryfiles

- schema_salad/metaschema.py
- schema_salad/metaschema/metaschema_base.yml
- schema_salad/tests/metaschema-pre.yml
Othwerwise the codegen code doesn't allow refering to arrays of custom types
Part of the fix for common-workflow-language/cwl-utils#71 & will fix (after another PR there) https://github.com/common-workflow-language/cwl-utils/issues/93
> ArraySchema.items is also TypeDSL

- schema_salad/ref_resolver.py
Fixes https://github.com/common-workflow-language/cwltool/issues/1505 and partially addresses https://github.com/common-workflow-language/cwl-utils/issues/71
Will still inject an `id` (or other identifier) in some circumstances.
For example with CWL: https://github.com/common-workflow-language/cwl-v1.2/blob/main/tests/schemadef-wf.cwl#L7 will result in `"id": "#schemadef-type.yml"` as part of the first entry in `requirements` as show below
``` cwl
{
"$graph": [
{
"class": "CommandLineTool",
"requirements": [
{
"class": "SchemaDefRequirement",
"types": [
{
"name": "#schemadef-type.yml/HelloType",
"type": "record",
"fields": [
{
"name": "#schemadef-type.yml/HelloType/a",
"type": "string"
},
{
"name": "#schemadef-type.yml/HelloType/b",
"type": "string"
}
]
}
],
"id": "#schemadef-type.yml"
} …
```
> resolver: inject fewer IDs

- .github/workflows/ci-tests.yml
The issue has been fixe by a new release of rdflib-jsonld
This reverts commit 9454285a15ce465ee6749ae3edb47dc473e4326b.
> Revert "setuptools 58 is not currently compatible"

- schema_salad/java_codegen.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
I'm proposing this as a fix for https://github.com/common-workflow-language/schema_salad/issues/320.
The java codegen had the same problems, which this PR also addresses.
> Fix primitive type loading for java and python codegen

- release-test.sh
- schema_salad/codegen.py
- schema_salad/java_codegen.py
- schema_salad/main.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/tests/test_python_codegen.py
After merging this request, a code generated parser provides a function `parser_info` that returns the specified constant string.
It enables users to distinguish code generated parsers with the return value of `parser_info`.
> Fix #473: Add `--codegen-parser-info`

- schema_salad/schema.py
- schema_salad/tests/test_avro_names.py
Because the avro-safe names are now namespaced (they didn't used to
be) we no longer want "out of vocabulary" symbols to be added as URLs.
Arvados-DCO-1.1-Signed-off-by: Peter Amstutz <peter.amstutz@curii.com>
> Symbols with inVocab: false should still have avro-safe names

- schema_salad/typescript/index.ts
- schema_salad/typescript/test/Typeguards.spec.ts
- schema_salad/typescript/util/Typeguards.ts
This PR fixes the undefined typeguard, so it returns true for `null` and `undefined` and not just `undefined`.
I also added ValidationException to the module exports, which was missing before.
> [TypeScript codegen] Fix undefined typeguard for null values

- schema_salad/java/main_utils/LoadingOptions.java
@ZimmerA Seems you already fixed this in your typescript implementation, but I remember that you reported a similar issue?
https://github.com/common-workflow-language/schema_salad/blob/74e909b532c7c5b12480421f9cfd06b3d7e24704/schema_salad/typescript/util/loaders/Loader.ts#L70
The fix is validated in cwljava: https://github.com/common-workflow-lab/cwljava/pull/62/files
> javacodegen scope check: chop off the correct end of the fragment

- schema_salad/typescript/package.json
- schema_salad/typescript/tsconfig.json
This adds some missing scripts and properties in package.json and tsconfig.json. I also added rimraf as a dependency, because rm -rf does not work on Windows.
> Update package json and tsconfig in typescript codegen

- schema_salad/java/pom.xml
> javacodegen: jackson-databind min version

- README.rst
I am not sure where the CommandLineTool.yml lives.
There is one version here: https://github.com/common-workflow-language/common-workflow-language/blob/main/v1.0/CommandLineTool.yml
and a second here: https://github.com/common-workflow-language/cwl-v1.2/blob/v1.2.0/CommandLineTool.yml
The first link seems outdated, but I am not 100% confident.
> Update links in README.md

- schema_salad/codegen.py
- schema_salad/tests/basket.yml
- schema_salad/tests/test_java_codegen.py
- schema_salad/tests/test_python_codegen.py
- schema_salad/tests/util.py
Fixes an issue reported by Simon Gene Gottlieb on Matrix:
>(...)
>With schema-salad-tool --codegen python CommonWorkflowLanguage.yaml and a very large python >documents falls out
>(...)
>Now I wanted to use the quick-start example, but I get some python error. I reduced the schema example >to:
```
- name: Basket
doc: A basket of products.
type: record
documentRoot: true
fields:
product: string
price: float
```
I used the schema above and a simple `test.yaml` with one record, and `schema-salad-tool schema.yaml test.yaml` passed with no errors. But the codegen gave me the same error (Simon was using Py3.10, I think, I'm on 3.9, FWIW).
Here's a quick fix for that, but that probably needs some review, e.g.:
* I think so
* Added one! :tada: 
* Ah! Because the error only happened when `$base` …
> Fix codegen error when a schema does not contain $base

- schema_salad/makedoc.py
Part of https://github.com/common-workflow-language/cwl-v1.2/issues/186
Didn't know schema salad was used in the generation of the HTML, good tip @tetron , thanks!
Before I started digging into how to change that font size, I realized we were using an older version of Bootstrap and that this could be upgraded. Luckily we have very little variation in the Bootstrap components and classes used, so it was really simple to upgrade to the latest release.
I tried using the same CDN provider, but I couldn't craft the URL for v5, so I used the CDN suggested in the Bootstrap 5 docs.
Thanks
Bruno
> Upgrade from Bootstrap 3 to Bootstrap 5

- schema_salad/tests/basket.yml
- schema_salad/tests/basket_schema.yml
see https://github.com/common-workflow-language/schema_salad/issues/541
It turns out that the code in the README was ok as is, but for some reason the first few times I tried it I could not get it to work at all, so I thought that the examples in the README were missing something. That led me to search in the history. 
After adding them to the repo I found that it worked. 
Note that I am not a python programmer, I am new to yaml, and to the whole project, so it could have been simple things like formatting that were the problem. But that is good reason to add those examples to the repository, and perhaps even test them with the unit tests (but I am not sure how to do that yet) 
```tcsh
$ schema-salad-tool basket_schema.yml basket.yml
/Users/hjs/Library/Python/3.8/bin/schema-salad-tool …
```
> add missing basket examples

- schema_salad/avro/schema.py
- schema_salad/tests/test_java_codegen.py
- schema_salad/tests/test_misc.py
- schema_salad/tests/test_python_codegen.py
- schema_salad/tests/test_schema/no_field_schema.yml
- schema_salad/tests/util.py
TODO:
How to I integrate a proper test for this? I added a `schema_salad/tests/empty_type_schema.yml` file and I would like to check that it can be validated.
The field SaladRecordSchema::fields is optional. see:
- https://www.commonwl.org/v1.2/SchemaSalad.html#SaladRecordSchema
- https://github.com/common-workflow-language/schema_salad/blob/d123d9c81fd22337e37a0b7e59f92019b0fdae3f/schema_salad/metaschema/metaschema_base.yml#L111
This repairs the validation.
> Fix: allow missing `fields` field in SaladRecordSchema

- schema_salad/dotnet_codegen.py
This PR fixes a bug in the code produced by the .net codegen that caused serializing documents with an id value of "None" (empty id) to crash the process.
> Dotnet codegen: fix id value serialization

- schema_salad/ref_resolver.py
- schema_salad/tests/missing_step_name.cwl
- schema_salad/tests/test_ref_resolver.py
Ref: https://github.com/common-workflow-language/cwltool/issues/1635
Before this PR:
```bash
(venv) kinow@ranma:~/Development/python/workspace/schema_salad$ schema-salad-tool schema_salad/tests/test_schema/CommonWorkflowLanguage.yml schema_salad/tests/missing_step_name.cwl
/home/kinow/Development/python/workspace/cwltool/venv/bin/schema-salad-tool Current version: 8.3.20220627005012
Document `schema_salad/tests/missing_step_name.cwl` failed validation:
mapSubject 'out' value 'None' is not a dict and does not have a mapPredicate.
```
After this PR:
```bash
(venv) kinow@ranma:~/Development/python/workspace/schema_salad$ schema-salad-tool schema_salad/tests/test_schema/CommonWorkflowLanguage.yml schema_salad/tests/missing_step_name.cwl …
```
> Use SourceLine in _resolve_idmap to include line number in error

- conftest.py
- schema_salad/tests/test_errors.py
I tried writing a fixture to reset the cache prior to each test execution. In theory I think this should fix the issue when loading metaschemas multiple times within a test, or in parallel.
> Fix release tests

- .gitignore
- mypy-stubs/rdflib/compare.pyi
- mypy-stubs/rdflib/graph.pyi
- schema_salad/fetcher.py
- schema_salad/metaschema.py
- schema_salad/python_codegen_support.py
- schema_salad/tests/test_python_codegen.py
This property loads schemas in a Graph object. This feature can be
used for CWL file formats checking.
> pycodegen: Added graph property to LoadingOptions

- schema_salad/codegen.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
- schema_salad/tests/test_python_codegen.py
Work in progress.  Fixing things to make the "fast validation" path in cwltool work.
> Codegen fixes

- schema_salad/metaschema.py
- schema_salad/python_codegen_support.py
Inspired by https://github.com/common-workflow-language/cwl-utils/issues/175 (though using YAML anchors & aliases is not supported by the CWL standards)
@ZimmerA Looks like the Typescript code has a similar problem, can you fix that in a separate PR?
> process secondaryFiles DSLs non-destructively

- .github/workflows/ci-tests.yml
except for wheel building as mypyc doesn't fully support Python 3.11
> CI: use the final release of Python 3.11

- .mergify.yml
- Duplicate keys (invalid YAML) were defined instead of simply using the list.
- Fixed a repeated word.
> resolve invalid definition in .mergify.yml

- schema_salad/cpp_codegen.py
msvc treats stdin, stdout, stderr as keywords (or maybe they are macros?). We need to escape these by adding an underscore "_".
> fix: cpp-generator escapes names stdin, stdout, stderr

- .github/workflows/ci-tests.yml
- schema_salad/cpp_codegen.py
Issues flagged by `bandit` locally were never reported in CI, and therefore never fixed unless the person making the PR ran tests locally.
Fixed `assert` used in code as flagged by `bandit`.
> add missing bandit to GitHub CI and apply bandit fixes

- schema_salad/dlang_codegen.py
This request fixes `@link` annotation in dlang codegen.
Current implementation considers only the case of `_type: @id` to add an annotation `@link` but `identity: true` is also needed as reported in #631.
> dlang: fix mis-annotated link annotation

- schema_salad/metaschema.py
- schema_salad/python_codegen_support.py
- schema_salad/ref_resolver.py
- schema_salad/tests/test_examples.py
- schema_salad/tests/test_real_cwl/bio-cwl-tools/bamtools_stats_invalid_schema_ref.cwl
Fixes:
```
gxformat2/schema/v19_09.py:167: error: Argument 1 to "__iadd__" of "Graph" has incompatible type "Union[str, Graph, bool]"; expected "Iterable[Tuple[Node, Node, Node]]"  [arg-type]
```
and should also be a little more helpful when the external schema can't be parsed or fetched (not familiar with the code base, but isn't there a need to be more transparent about this??).
> Avoid mypy error on adding newGraph from cache to graph

- schema_salad/ref_resolver.py
- schema_salad/tests/test_ref_resolver.py
For consistency with cwltool fast parser
> ref_resolver index makes entries for import: and include:

- Makefile
- requirements.txt
- schema_salad/avro/schema.py
- schema_salad/codegen.py
- schema_salad/cpp_codegen.py
- schema_salad/dlang_codegen.py
- schema_salad/dotnet_codegen.py
- schema_salad/fetcher.py
- schema_salad/java_codegen.py
- schema_salad/makedoc.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
- schema_salad/schema.py
- schema_salad/tests/test_pickling.py
- schema_salad/typescript_codegen.py
- schema_salad/validate.py
- setup.py
> make avro objects serializable & Pickle testing

- mypy-stubs/rdflib/plugin.pyi
- schema_salad/ref_resolver.py
- schema_salad/tests/revtool_bad_schema.cwl
- schema_salad/tests/test_examples.py
bad content, missing parsing (RDFa) plugin, and more
> cope with more types of errors when attempting to load $schemas

- schema_salad/metaschema.py
- schema_salad/metaschema/metaschema_base.yml
- schema_salad/python_codegen.py
- schema_salad/tests/metaschema-pre.yml
- schema_salad/tests/test_makedoc.py
Bonus: Python codegen: preserve enum doc fields
> PrimitiveType is a list of type **names**; not a list of types.

- .github/workflows/ci-tests.yml
- Makefile
- mypy-requirements.txt
- schema_salad/tests/memory-leak-check.py
- setup.py
- tox.ini
To prove the test, reverse the changes to `setup.py` and run `tox -r py311-memleak`
> exceptions.py: don't compile with mypyc to prevent memory leaks

- tox.ini
Currently running `tox -e py310-unit` will only run the unit tests the first time the command is run. 
This is because `make coverage-report` (the command that tox runs for the unit tests) checks to see .coverage exists. However, .coverage is created the first time and not deleted so the tests will not be rerun. The simplest solution with the least amount of potential downstream issues would be to add a `--always-make` flag in the tox.ini file.
> Always re-run unittests

- schema_salad/metaschema/metaschema_base.yml
- schema_salad/tests/metaschema-pre.yml
- schema_salad/tests/test_makedoc.py
This request is to solve #716 by clarifying:
- an array such as `[int, string]` indicates a union type of its elements, and
- its elements may be duplicated.
> Add description of union types

- schema_salad/codegen.py
- schema_salad/dlang_codegen.py
This request makes the `saladVersion` field supported by the dlang code-generated parser.
This change is already tested with [schema-salad-d](https://github.com/tom-tan/schema-salad-d) commit: 1170e1b1.
It improves the error and warning messages when users use version-specific or platform-specific features such as supporting nested typeDSL.
This request does not include such changes but they will be done in the [schema-salad-d](https://github.com/tom-tan/schema-salad-d) rather than the code-generated parser.
TODO:
> dlang: support `saladVersion`

- .circleci/config.yml
- .github/workflows/wheels.yml
- cibw-requirements.txt
- pyproject.toml
- stop building Python3.7 wheels
- switch to native cibuildwheel; RalfG/python-wheels-manylinux-build is deprecated
> release no py37 wheels

- schema_salad/codegen.py
- schema_salad/codegen_base.py
- schema_salad/dotnet/util/Loaders/UriLoader.cs
- schema_salad/dotnet/util/LoadingOptions.cs
- schema_salad/dotnet_codegen.py
- schema_salad/java/main_utils/LoadingOptions.java
- schema_salad/java/main_utils/LoadingOptionsBuilder.java
- schema_salad/java/main_utils/UriLoader.java
- schema_salad/java_codegen.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
- schema_salad/typescript/util/LoadingOptions.ts
- schema_salad/typescript/util/loaders/UriLoader.ts
- schema_salad/typescript_codegen.py
This commit introduces support for the `noLinkCheck` `jsonldPredicate` in the Schema SALAD codegen toolchain, and in particular in the `URILoader` stack. When `noLinkCheck` is set to `true`, no link checking is performed for all the underlying objects hierarchy. The need to propagate its value to the hierarchy makes it necessary to modify also the `LoadingOptions` data structure.
All parsers but the Python one never perform link checking up to now, so this update makes no modification to their actual behaviour. However, it enables the `URILoader` classes to receive the `noLinkCheck` parameter for future implementations.
> Add support for `noLinkCheck` in codegen

- schema_salad/validate.py
NamedUnionSchema isn't a subclass of UnionSchema, and the first thing I tried (making NamedUnionSchema a subclass of both UnionSchema and NamedSchema) didn't work because mypyc didn't like multiple inheritance.
This should fix https://github.com/common-workflow-language/cwltool/pull/1779
> check for both UnionSchema and NamedUnionSchema 

- schema_salad/dotnet_codegen.py
- schema_salad/java_codegen.py
Quite similar to https://github.com/common-workflow-language/schema_salad/pull/829/commits/6d85020dae720722ddd623db0349d8bd2736715c and fixes building the java code for gxformat2.
> Fix java code generator emitting unknown None symbol

- schema_salad/exceptions.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/python_codegen_support.py
- schema_salad/tests/test_codegen_errors.py
This gxformat2 document has a wrong type on the max of a float parameter.
```
class: GalaxyWorkflow
doc: |
Simple workflow that no-op cats a file.
inputs:
the_input:
type: File
doc: input doc
the_collection:
type: collection
collection_type: list
the_integer:
type: int
min: 1
max: 3
the_float:
type: float
min: 1.0
max: 3.0a
outputs:
the_output:
outputSource: cat/out_file1
steps:
cat:
tool_id: cat1
doc: cat doc
in:
input1: the_input
```
Before:
```
.. ERROR: Validation failed schema/v19_09/examples/valid1.yml:1:1:   Object `valid1.yml` is not valid because:
schema/v19_09/examples/valid1.yml:4:1:     the `inputs` field is not valid because:
array item is invalid because
schema/v19_09/examples/valid1.yml:15:3:       checking object `valid1.yml#the_float`
* checking object …
```
> error messages: report model and value being checked

- .circleci/config.yml
- .github/workflows/wheels.yml
> musl libc 1.1 is EOL and Alpine Linux 3.12 also (support ended 2 years ago, May 1st, 2022).
https://github.com/pypa/manylinux/issues/1629
> wheels: drop musllinux 1.1

- Makefile
- schema_salad/cpp_codegen.py
- schema_salad/tests/cpp_tests/01_single_record.h
- schema_salad/tests/cpp_tests/02_two_records.h
- schema_salad/tests/cpp_tests/03_simple_inheritance.h
- schema_salad/tests/cpp_tests/04_abstract_inheritance.h
- schema_salad/tests/cpp_tests/05_specialization.h
Currently, types of 'any' are simply ignored when generating output. This improves the handling of 'any' by adding explicit conversions to:
- float
- double
- char
- int8_t
- uint8_t
- int16_t
- uint16_t
- int32_t
- uint32_t
- int64_t
- uint64_t and
- std::string
required to fix https://github.com/deNBI-cibi/tool_description_lib/issues/59
also uploaded a new generated version to: https://github.com/common-workflow-lab/cwl-cpp-auto/pull/11
> cppgen: improved support of fields of type 'any'

- schema_salad/codegen.py
- schema_salad/metaschema.py
- schema_salad/python_codegen.py
- schema_salad/tests/test_codegen_errors.py
This commit asjusts the Python generated parser to correctly deal with namespaced classes (e.g., those coming from cwltool extensions).
> Fix class detection for namespaced classes (Py)

- schema_salad/metaschema.py
- schema_salad/python_codegen.py
This commit ensures that namespaced class names (e.g., those coming from `cwltool` extensions) are correctly saved by the `save` method of the `Saveable` class. Before this commit, the prefix was lost during this process.
> Fixed `save` method for namespaced `class` fields

- schema_salad/python_codegen.py
This commit simplifies handling full class uris in three ways. It removes the `class_uri` field and retrieves the full class uri directly from the `rvocab` data structure
> Improve class uri handling

- schema_salad/java/main_utils/UnionLoader.java
- schema_salad/java_codegen.py
- java codegen: use double quotes for string literals in generated code.
- java codegen: UnionLoader.alternates needs a concrete collection type.
> Fixes for Java codegen

- schema_salad/java_codegen.py
> java codegen: expose the extension fields
