schema_salad/aslist.py

Ready for review & merge, @tetron

restore missing file from PyPI release

---

.travis.yml
requirements.txt
schema_salad/__init__.py
schema_salad/__main__.py
schema_salad/add_dictlist.py
schema_salad/aslist.py
schema_salad/flatten.py
schema_salad/jsonld_context.py
schema_salad/main.py
schema_salad/makedoc.py
schema_salad/ref_resolver.py
schema_salad/schema.py
schema_salad/validate.py
setup.py
tests/test_examples.py
tox.ini

```
pip3 install mypy-lang # --user if needed
mypy --py2 --implicit-any --silent-imports schema_salad # noisy, but useful
```

python3 compatibility & optional static typing

---

Makefile

In preparation for converting to Python 3 with Py2 compat

measure code coverage

---

schema_salad/main.py
schema_salad/metaschema/metaschema.yml
schema_salad/ref_resolver.py
schema_salad/schema.py
setup.py
tests/test_examples.py

Support fields containing references which search upward scope.

Scoped ref

---

schema_salad/makedoc.py

This reverts commit a58b955afebfefe0e407281ca694ddcf63439549.

Revert "make explicit optional and required fields"

---

schema_salad/ref_resolver.py
schema_salad/tests/test_ref_resolver.py

Currently it falls over is HOME environment variable is not set.

Make ref_resolver.Loader more fault tolerant

---

schema_salad/validate.py
setup.py

Separate strictness of checking foreign properties from strict checking of primary properties.

Relax strict checking foreign properties

---

schema_salad/main.py
schema_salad/ref_resolver.py
schema_salad/schema.py
schema_salad/sourceline.py
schema_salad/tests/test_errors.py
schema_salad/tests/test_schema/test12.cwl
schema_salad/tests/test_schema/test13.cwl
schema_salad/tests/test_schema/test14.cwl
setup.py

Check if IDs are duplicated in schema_salad itself. Throw exception on finding duplicate IDs.
Fix for #56

Validating Ids for duplicate Issue#56

---

schema_salad/validate.py

When record class doesn't match expectation.

Validation fix.  Must raise exception when raise_ex is true 

---

Makefile
mypy_requirements.txt
requirements.txt
tox.ini

Should fix: https://github.com/common-workflow-language/schema_salad/pull/111#issuecomment-310699909

requirements.txt: add mypy, typed-ast packages, use in tox and Makefile

---

README.rst
appveyor.yml
schema_salad/main.py
schema_salad/ref_resolver.py
schema_salad/tests/test_examples.py
schema_salad/tests/test_fetch.py
schema_salad/tests/util.py

[WIP]windows support: added appveyor.yml for windows testing and Integration

---

schema_salad/ref_resolver.py

modified urljoin: on windows it was ignoring Drive names when constructing final url. Important to merge for windows compatibility.

Windows minor fix: In urljoin function

---

mypy_requirements.txt
schema_salad/makedoc.py
schema_salad/ref_resolver.py

https://mypy-lang.blogspot.in/

[MRG] update mypy to 0.520 

---

requirements.txt
setup.py

- Includes changes made by @kapilkd13 in https://github.com/common-workflow-language/avro/pull/1
- https://pypi.python.org/pypi/avro-cwl/1.8.4

Bump version of `avro` for Python 3

---

schema_salad/tests/test_errors.py
schema_salad/tests/test_print_oneline.py
schema_salad/tests/test_schema/test15.cwl

This request adds a test case for Issue #135.
I used the same example in #135 for the test case but its file name is changed to `test15.cwl`.
I confirmed it passes `make test`.

Add test for Issue #135

---

schema_salad/ref_resolver.py

Also cache results of check_exists().

Make exceptions loading extension schemas non-fatal.

---

.travis.yml
release-test.sh

plus miscellaneous shellcheck fixes

Travis fix for forks

---

schema_salad/makedoc.py

Fix type rendering of "steps"

---

schema_salad/jsonld_context.py
schema_salad/main.py
schema_salad/ref_resolver.py

From reviewing https://github.com/common-workflow-language/cwltool/issues/839 but it doesn't fix the issue

Use CommentedMap() as appropriate

---

.coveragerc
Makefile
schema_salad/avro/schema.py
schema_salad/main.py
schema_salad/schema.py
schema_salad/tests/bad_schema.yml
schema_salad/tests/test_errors.py
schema_salad/validate.py
setup.py
tox.ini

throw SchemaParseException instead of returning it

---

schema_salad/makedoc.py

The other half of the fix for https://github.com/common-workflow-language/common-workflow-language/issues/529

add link to map explanation

---

.travis.yml
Makefile
release-test.sh
requirements.txt
schema_salad/metaschema.py
schema_salad/python_codegen.py
schema_salad/python_codegen_support.py
schema_salad/tests/test_cg.py
setup.py
tox.ini

codegen: add plain initializers

---

.flake8
schema_salad/tests/test_ref_resolver.py
setup.py
tox.ini

This caused build failures for Debian as the build path had uppercase characters in it

tests: do not lower case the path

---

schema_salad/metaschema.py
schema_salad/python_codegen.py
schema_salad/python_codegen_support.py
schema_salad/ref_resolver.py
tox.ini

Optional base_url causes mypy typechecking error.

base_url parameter to urljoin shouldn't be optional.

---

schema_salad/makedoc.py

Fix doc generation refactor t -> entry

---

schema_salad/metaschema.py
schema_salad/python_codegen.py

It is a continuation of #284.
It applies tree structured exception to codegen.

Use structured exception for codegen

---

schema_salad/main.py
schema_salad/ref_resolver.py
schema_salad/tests/test_errors.py
schema_salad/tests/test_examples.py
schema_salad/tests/test_fetch.py
schema_salad/tests/test_fp.py
schema_salad/tests/test_print_oneline.py
schema_salad/tests/test_real_cwl.py

Some changes came with `black` version 19.10b0

update black formatting

---

schema_salad/makedoc.py

xref https://github.com/jmchilton/gxformat2/commit/8d81551f3ffb2fc7992e760233a9fc1c80ac26e8

More options to customize docs.

---

schema_salad/java_codegen.py

- Spelling fix.
- Fix test resource handling to allow repeatedly calling codegen for iterative updates.

More java codegen fixes.

---

Makefile
requirements.txt
setup.py

Update max ruaml.yaml version to 0.16.5 in setup.py and requirements.txt. Update Makefile mypy target as suggested in setup.py.

Feature/try ruaml yaml 0.16.5

---

schema_salad/codegen.py
schema_salad/codegen_base.py
schema_salad/fetcher.py
schema_salad/java_codegen.py
schema_salad/jsonld_context.py
schema_salad/main.py
schema_salad/metaschema.py
schema_salad/python_codegen.py
schema_salad/python_codegen_support.py
schema_salad/ref_resolver.py
schema_salad/schema.py
schema_salad/tests/test_cwl11.py
schema_salad/tests/test_examples.py
schema_salad/tests/test_real_cwl/bio-cwl-tools/bamtools_stats.cwl
schema_salad/tests/test_real_cwl/bio-cwl-tools/picard_CreateSequenceDictionary.cwl
schema_salad/tests/test_ref_resolver.py
schema_salad/tests/test_schemas_directive.py
schema_salad/utils.py

Redo of #357 with idiomatic pytesting and other fixes from @mr-c 
partially addresses #349

CWL v1.1+ python codegen support [redo]

---

Makefile
schema_salad/avro/schema.py
schema_salad/codegen.py
schema_salad/codegen_base.py
schema_salad/exceptions.py
schema_salad/fetcher.py
schema_salad/java_codegen.py
schema_salad/jsonld_context.py
schema_salad/main.py
schema_salad/makedoc.py
schema_salad/metaschema.py
schema_salad/python_codegen.py
schema_salad/python_codegen_support.py
schema_salad/ref_resolver.py
schema_salad/schema.py
schema_salad/sourceline.py
schema_salad/tests/matcher.py
schema_salad/tests/test_cg.py
schema_salad/tests/test_cwl11.py
schema_salad/tests/test_examples.py
schema_salad/tests/test_fetch.py
schema_salad/tests/test_print_oneline.py
schema_salad/tests/test_python_codegen.py
schema_salad/tests/test_ref_resolver.py
schema_salad/validate.py
setup.py

Many thanks to @nsoranzo for introducing me to `pyupgrade`!

pyupgrade to 3.6 syntax

---

schema_salad/main.py
schema_salad/makedoc.py

See commits for details.
Fixes #418

Three small fixes

---

.github/workflows/ci-tests.yml
.github/workflows/wheels.yml

Added linux aarch64 wheel build support.
Related to #419. @mr-c, Could you please review this PR?

Add linux aarch64 wheel build support

---

Makefile
schema_salad/jsonld_context.py
schema_salad/main.py
schema_salad/tests/test_examples.py
setup.py
tox.ini

Fixes https://github.com/common-workflow-language/cwltool/issues/1379

cope with datetimes when dumping JSON

---

schema_salad/metaschema.py
schema_salad/python_codegen.py

The Python version of https://github.com/common-workflow-language/schema_salad/pull/423
Part of the fix for common-workflow-language/cwl-utils#71

pycodegen: deal with anonymous types better

---

schema_salad/metaschema.py
schema_salad/metaschema/metaschema_base.yml
schema_salad/tests/metaschema-pre.yml

This reverts commit 5fccc555ad47e385a804659f2f50fb1667416c55.
Further testing revealed that it didn't fix anything

Revert "ArraySchema.items is also TypeDSL"

---

schema_salad/fetcher.py

Link existence checking should follow redirects

---

.github/workflows/ci-tests.yml
Makefile
schema_salad/makedoc.py
tox.ini

Fixes #426
Didn't have a chance to write a test, makedoc currently lacks a testing framework.

Don't expose avro namespaces in makedoc.

---

release-test.sh

fixes Python 3.10 + manylinux wheel download & caching

release-test: newer pip

---

schema_salad/metaschema/import_include.md
schema_salad/tests/metaschema-pre.yml

It fixes #478 by clarifying the flattened case.
It also adds an example of flattened import.

Fix document of import

---

schema_salad/typescript/package.json

@ZimmerA Maybe check to see if there are other changes to pull over from https://github.com/common-workflow-lab/cwl-ts-auto/blob/b00f15ab8ba6bc4ff07db0288a5c43391770daf2/package.json ?

typescript: add documentation generation command

---

schema_salad/java/main_utils/SecondaryFilesDslLoader.java

@ZimmerA Maybe this fix is needed for typescript as well?
Fixes #525

java/pycodegen: don't modify as we parse secondaryFiles

---

schema_salad/java/main_utils/Uris.java
schema_salad/java/test_utils/ShortnameTest.java
schema_salad/metaschema.py
schema_salad/python_codegen_support.py
schema_salad/tests/test_cg.py
schema_salad/typescript/index.ts
schema_salad/typescript/test/utilities.spec.ts
schema_salad/typescript/util/Saveable.ts

@ZimmerA Do you want me to keep this open so you can add a TypeScript `shortname` function + tests?

Codegen shortname

---

README.rst

Quick correction to minimum version of Python supported.

Correct minimum python requirement

---

schema_salad/avro/schema.py
schema_salad/schema.py
schema_salad/tests/inherited-attributes.yml
schema_salad/tests/test_makedoc.py
schema_salad/tests/test_subtypes.py

Closes #555 
(for now this PR contains only a test to reproduce the error.)

Fix documentation generated of inherited types

---

schema_salad/schema.py
schema_salad/tests/test_examples.py
schema_salad/tests/test_misc.py
schema_salad/tests/test_schema/misc_schema_v1.yml
schema_salad/tests/test_schema/misc_schema_v2.yml

Duplicate the loader cache to avoid conflicts.  Going to test a bit more thoroughly before putting it up for merge.

Attempt to fix metaschema caching

---

schema_salad/utils.py

To assist cwltool: https://github.com/common-workflow-language/cwltool/pull/1720/files#diff-7bc82a2b4dbfbc386a1c1d22dac00140d782b959e858cd99978fc3ee193d15f2R463

add MandatoryResolveType

---

requirements.txt
setup.py

use filecache extra for Cachecontrol to get the correct dependency

---

schema_salad/__init__.py

needed until https://github.com/psf/requests/issues/6240 is fixed

Py3.6: Ignore requests package warning about chardet 5

---

setup.py

Broken in 49cf3a72a52a39bc096cb807db78eb616ab8c227 .

Support any Python 3.11.x patch versions

---

schema_salad/tests/test_cwl11.py
schema_salad/tests/test_errors.py
schema_salad/validate.py

Fixes https://github.com/common-workflow-language/cwltool/issues/1199

Better message when dictionary (object) expected.

---

.github/workflows/ci-tests.yml
CONTRIBUTING.md
Makefile
README.rst
dev-requirements.txt
pyproject.toml
requirements.txt
schema_salad/codegen.py
schema_salad/main.py
schema_salad/sourceline.py
setup.py
tox.ini

Python 3.8 is now the minimum version

drop support for Python 3.6

---

schema_salad/cpp_codegen.py

This PR is ok when this PR passes: https://github.com/common-workflow-lab/cwl-cpp-auto/pull/7

fix: code compatible with clang

---

schema_salad/fetcher.py

Discussed in [issue#747](https://github.com/common-workflow-language/schema_salad/issues/747)

Fix to work even if there are multiple Content-Type headers

---

schema_salad/cpp_codegen.py
schema_salad/tests/cpp_tests/01_single_record.h
schema_salad/tests/cpp_tests/02_two_records.h
schema_salad/tests/cpp_tests/03_simple_inheritance.h
schema_salad/tests/cpp_tests/04_abstract_inheritance.h
schema_salad/tests/cpp_tests/05_specialization.h

Improves the c++ generation.
This should only be merged if PR https://github.com/common-workflow-lab/cwl-cpp-auto/pull/9 and https://github.com/deNBI-cibi/tool_description_lib/pull/47 successfully pass all CI checks.
And https://github.com/OpenMS/OpenMS/pull/6156 must pass everything except of "CodeFactor" and "apple_clang" checks

fix: improved cpp generation (msvc 14.24)

---

.github/workflows/ci-tests.yml
Makefile
dev-requirements.txt
lint-requirements.txt
schema_salad/__init__.py
schema_salad/metaschema.py
schema_salad/python_codegen.py
schema_salad/python_codegen_support.py
schema_salad/tests/test_codegen_errors.py
schema_salad/tests/test_cpp_codegen.py
tox.ini

- dev: consolidate lint checks, add diff-pylint and diff-pydocstyle
- pyupgrade refresh

lint consolidation

---

.github/workflows/ci-tests.yml
.github/workflows/wheels.yml
Makefile
mypy-stubs/cachecontrol/caches/__init__.pyi
mypy-stubs/cachecontrol/caches/file_cache.pyi
pyproject.toml
schema_salad/dlang_codegen.py
schema_salad/tests/test_codegen_errors.py
schema_salad/tests/test_cwl11.py
schema_salad/tests/test_errors.py
schema_salad/tests/test_print_oneline.py
setup.py
tox.ini

- no mypyc support yet
Fixes #864

test with Python 3.13.0-rc1

---

schema_salad/dotnet/util/Loaders/IdMapLoader.cs
schema_salad/java/main_utils/IdMapLoader.java
schema_salad/metaschema.py
schema_salad/python_codegen_support.py
schema_salad/tests/cwl-pre.yml
schema_salad/tests/metaschema-pre.yml
schema_salad/tests/test_cg.py
schema_salad/typescript/test/IdMap.spec.ts
schema_salad/typescript/util/loaders/IdMapLoader.ts

Inspired by https://github.com/common-workflow-language/cwl-v1.3/issues/62

codegen: remove unnecessary sorting of keys in ID Maps
